# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Backube blog
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Backube Project is building data protection solutions for Kubernetes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: BackubeProject
#github_username:  Backube

# Configuration for mimima theme
# https://github.com/jekyll/minima
#author:
#  name: The Backube Project
minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/backube" }
    - { platform: twitter,        user_url: "https://twitter.com/BackubeProject" }
google_analytics: UA-154117660-2
show_drafts: false
show_excerpts: true

# Build settings
markdown: kramdown
# https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll
# To use a supported theme:
#theme: minima
# To use any jekyll theme on GH:
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  # https://github-emoji-list.herokuapp.com/
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Mandatory settings for GH pages
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
